### ISSUE TITLE
Weapon Poison (++) not showing dose count

### ISSUE THREAD

**Issue by evilgenious448** [mrchooch/potion-bars#2]
As you can see in screenshot below, it doesn't show doses for Weapon Poison (++)
![image](https://github.com/user-attachments/assets/5b24d03c-0ec7-4017-8238-40a6e10a8f62)

With the plugin disabled, it does show:
![image](https://github.com/user-attachments/assets/c7d96206-4e6a-4c58-b65b-3e8a4ecf684d)

Seems like it is because Weapon poison is a "Quantity" not a "Doses"

Haven't tested for any other weapon poison variants, so might be worth checking those.

Thanks!

**Comment by mrchooch** [comment]
Fixed, along with unfinished potions! Changes should go live sometime today
